In [1]:
from keras.models import load_model

Using TensorFlow backend.


In [2]:
model= load_model('facedetect.h5')

In [3]:

import cv2
import numpy as np
import PIL
import IPython.display as ipd
from keras.preprocessing import image

In [4]:
face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [5]:
def face_detect(img, size=0.5):
    # Convert image to gray
    gray  = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray, 1.3, 5)
    if faces is ():
        return img, []
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        face = img[y:y+h, x:x+w]
        face = cv2.resize(face, (224, 224))          
    return img, face

In [9]:
# Open Webcam
cap = cv2.VideoCapture(0)

while True:

    ret, img = cap.read()

    image, face = face_detect(img)
    face=np.array(face)
    face= np.expand_dims(face, axis=0)
    if(face.shape==(1,0)):
        cv2.putText(image, "I don't know", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,0,255), 2)
        cv2.imshow('Face Recognition prediction', image )
    
    else:
        results = model.predict(face)
        print(results)
        if(results[0][0] == 1.0):
            cv2.putText(image, "Akshit", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
            cv2.imshow('Face Recognition prediction', image )

        if(results[0][0] != 1.0):
            cv2.putText(image, "Dharmesh", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
            cv2.imshow('Face Recognition prediction', image )
            
    if cv2.waitKey(1) == 13:
        break

cap.release()
cv2.destroyAllWindows()

[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[0.99650335 0.00349665]]
[[9.9997771e-01 2.2347676e-05]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1.0000000e+00 2.7781207e-22]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[6.705951e-13 1.000000e+00]]
[[1. 0.]]
[[1.0000000e+00 6.4562422e-15]]
[[9.9999976e-01 2.2653083e-07]]
[[1. 0.]]
[[1.000000e+00 1.763476e-16]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1.4540236e-06 9.9999857e-01]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1.0000000e+00 1.0969976e-19]]
[[1.0338157e-15 1.0000000e+00]]
[[2.9417207e-15 1.0000000e+00]]
[[6.6897586e-22 1.0000000e+00]]
[[1.00000e+00 1.75293e-19]]
[[1.000000e+00 2.078078e-34]]
[[9.999995e-01 5.002508e-07]]
[[1.000000e+00 8.375747e-21]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
